@startuml "Plataforma de Cursos de Idiomas Online"
left to right direction

:Aluno: as aluno


rectangle "Plataforma de Cursos de Idiomas Online"{
    (Visualizar Curso) as visualizar_curso
    (Visualizar Aula do Curso) as visualizar_aula_curso
    (Listar Aulas do Curso) as listar_aulas_curso

    (Realizar Login) as realizar_login

    (Fazer Cadastro como Aluno) as fazer_cadastro_aluno
    ' (Visualizar Perfil de Aluno) as visualizar_perfil_aluno
    ' (Atualizar Perfil de Aluno) as atualizar_perfil_aluno
    (Visualizar Cursos Disponíveis) as visualizar_cursos_disponiveis
    ' (Filtrar Listagem de Cursos) as filtrar_listagem_cursos
    ' (Buscar Curso) as buscar_curso
    (Fazer Inscrição em Curso) as fazer_inscricao_curso
    (Cancelar Inscrição em Curso) as cancelar_inscricao_curso
    (Assistir Aula) as assistir_aula
    (Listar Aulas Assistidas do Curso) as listar_aulas_assistidas_curso
    (Solicitar Tutoria) as solicitar_tutoria
    (Cancelar Solicitação de Tutoria) as cancelar_solicitacao_tutoria
    (Solicitar Certificado de Curso) as solicitar_certificado_curso
    (Visualizar Certificado de Curso) as visualizar_certificado_curso
    (Listar Certificados Adquiridos) as listar_certificados_adquiridos
    ' (Avaliar Curso) as avaliar_curso
    ' (Fazer Comentário em Chat de Aula) as fazer_comentario_chat_aula
    ' (Responder Comentário em Chat de Aula) as responder_comentario_chat_aula
}

aluno --> fazer_cadastro_aluno
aluno --> realizar_login

aluno --> visualizar_cursos_disponiveis

aluno --> fazer_inscricao_curso
aluno --> visualizar_curso

visualizar_curso <.down. cancelar_inscricao_curso: <<extend>
visualizar_curso <.down. listar_aulas_curso: <<extend>
visualizar_curso <.down. solicitar_certificado_curso: <<extend>

listar_aulas_curso <.down. visualizar_aula_curso: <<extend>
listar_aulas_curso <.down. listar_aulas_assistidas_curso: <<extend>

visualizar_aula_curso <.up. assistir_aula: <<extend>

aluno --> listar_certificados_adquiridos

listar_certificados_adquiridos <.down. visualizar_certificado_curso: <<extend>

aluno --> solicitar_tutoria
aluno --> cancelar_solicitacao_tutoria

@enduml