@startuml "Selecionar Evento"
hide footbox
actor Cliente as cliente_ator
participant TelaListaEventos as tela_lista_eventos
participant ControleEvento as controle_evento
participant TelaEvento as tela_evento
participant Evento as evento
participant ControleIngresso as controle_ingresso

database BD as bd
cliente_ator -> tela_lista_eventos: selecionarEvento(id_evento: String)
activate tela_lista_eventos

tela_lista_eventos -> controle_evento: buscarEvento(id_evento: String): Evento
activate controle_evento

controle_evento -> bd: consultar(id_evento: String): String[]
activate bd

bd --> controle_evento
deactivate bd

controle_evento -> evento**: <<create>>
activate evento

controle_evento --> tela_lista_eventos
deactivate controle_evento
deactivate tela_lista_eventos

@enduml