@startuml "Modelo de Classes - Aluno"
left to right direction

abstract class Usuario {
    -id: String
    -nome: String
    -email: String
    -senha: String
}

class Aluno <<entity>> {
    -matricula: String
    -cursosInscritos: List<Curso>
    -tutoriasSolicitadas: List<Tutoria>
    -certificados: List<Certificado>
    -aulasAssistidas: List<Aula>
}

class Professor <<entity>> {
    -cursosMinistrados: List<Curso>
    -tutorias: List<Tutoria>
}

class Curso <<entity>> {
    -id: String
    -titulo: String
    -descricao: String
    -professor: Professor
    -aulas: List<Aula>
    -idioma: String
    -duracao: int
    -alunosCadastrados: List<Aluno>
    -certificado: Certificado
}

class Aula <<entity>> {
    -id: String
    -titulo: String
    -conteudo: String
    -duracao: int
    -curso: Curso
}

class Certificado <<entity>> {
    -id: String
    -aluno: Aluno
    -curso: Curso
    -dataEmissao: Date
}

class Tutoria <<entity>> {
    -id: String
    -aluno: Aluno
    -professor: Professor
    -horario: Date
    -status: String
}

class ControleAluno {
    +realizarCadastro(*args): Aluno
    +atualizarDados(*args): Aluno
    +realizarLogin(email: String, senha: String): boolean
}

class ControleProfessor {
    +realizarCadastro(*args): Professor
    +atualizarDados(*args): Professor
    +realizarLogin(email: String, senha: String): boolean
}

class ControleAula {
    +assistirAula(aluno: Aluno, aula: Aula): boolean
    +listarAulasDisponiveis(id_curso: String): List<Aula>
    +listarAulasAssistidas(id_aluno: String): List<Aula>
    +cadastrarAula(*args): Aula
    +atualizarAula(*args): Aula
    +excluirAula(id_aula: String): boolean
}

class ControleCurso {
    +listarCursosDisponiveis(): List<Curso>
    +buscarCurso(id_curso: String): Curso
    +inscreverAluno(aluno: Aluno, curso: Curso): boolean
    +cancelarInscricao(aluno: Aluno, curso: Curso): boolean
    +cadastrarCurso(*args): Curso
    +atualizarCurso(*args): Curso
    +excluirCurso(id_curso: String): boolean
    +listarAlunosCadastrados(id_curso: String): List<Aluno>
}

class ControleTutoria {
    +listarTutoresDisponiveis(id_curso: String): List<Professor>
    +solicitarTutoria(id_aluno: String, id_professor: String, horario: Date): Tutoria
    +cancelarTutoria(id_tutoria): boolean
    +listarTutoriasAluno(id_aluno: String): List<Tutoria>
    +listarTutoriasProfessor(id_professor: String): List<Tutoria>
}

class ControleCertificado {
    +emitirCertificado(id_aluno: String, id_curso: String): Certificado
    +baixarCertificado(id_certificado: String): File
    +listarCertificadosAluno(id_aluno: String): List<Certificado>
}

class TelaCurso {
    -campo_titulo: String
    -campo_descricao: String
    -campo_professor: String
    -campo_aulas: String []
    -campo_idioma: String
    -campo_duracao: int
    -campo_alunosCadastrados: String []
    -botao_enviar: Button
    +enviar(*args): String
}

class TelaListaCurso{
    -selecionarCurso(id_curso: String): void
}

class TelaAula {
    -campo_titulo: String
    -campo_conteudo: String
    -campo_duracao: int
    -campo_curso: String
    -botao_enviar: Button
    +enviar(*args): String
}

class TelaListaAula{
    -selecionarAula(id_aula: String): void
}

class TelaAluno {
    -campo_nome: String
    -campo_email: String
    -campo_senha: String
    -campo_matricula: String
    -campo_cursosInscritos: String []
    -campo_tutoriasSolicitadas: String []
    -campo_certificados: String []
    -campo_aulasAssistidas: String []
    -botao_enviar: Button
    +enviar(*args): String
}

class TelaListaAluno{
    -selecionarAluno(id_aluno: String): void
}

class TelaProfessor {
    -campo_nome: String
    -campo_email: String
    -campo_senha: String
    -campo_cursosMinistrados: String []
    -campo_tutorias: String []
    -botao_enviar: Button
    +enviar(*args): String
}

class TelaListaProfessor{
    -selecionarProfessor(id_professor: String): void
}

class TelaTutoria {
    -campo_aluno: String
    -campo_professor: String
    -campo_horario: Date
    -campo_status: String
    -botao_enviar: Button
    +enviar(*args): String
}

class TelaListaTutoria{
    -selecionarTutoria(id_tutoria: String): void
}

class TelaCertificado {
    -campo_aluno: String
    -campo_curso: String
    -campo_dataEmissao: Date
    -botao_enviar: Button
    +enviar(*args): String
}

class TelaListaCertificado{
    -selecionarCertificado(id_certificado: String): void
}


Aluno --|> Usuario
Professor --|> Usuario

Professor "1" -- "0..*" Curso: < Ministra
Certificado "1" -- "1" Curso: < Emitido
Aluno "0..*" -- "0..*" Curso: < Inscrito

Aluno "1..*" -- "0..*" Tutoria: < Solicita
Professor "1*" -- "0..*" Tutoria: < Participa

Aluno "0..*" -- "0..*" Aula: < Assiste
Professor "0..*" -- "0..*" Aula: < Cadastra

Aluno "1*" -- "0..*" Certificado: < Possui

ControleAluno -- Aluno: Controla >
ControleCurso -- Curso: Controla >
ControleTutoria -- Tutoria: Controla >
ControleCertificado -- Certificado: Controla >
ControleProfessor -- Professor: Controla >
ControleAula -- Aula: Controla >

@enduml